# Stolen from https://github.com/codecov/example-c/blob/master/.travis.yml
language: c++
sudo: false
script:
        - CXX=g++ CFLAGS=-coverage make
        - ./bin/test

after_success:
        # Maybe we'll try code coverage again sometime
        #- bash <(curl -s https://codecov.io/bash)
        - gcov network.cpp
